---
version: 1.2.0 # Struct spec version https://github.com/lyptt/struct/wiki/Specfile-format:-v1.2.0

#=== GLOBAL SETTINGS ===

_: &CompanyIdentifier khatskevich.maxim
_: &ProjectTitle MKHRequirement

#=== SHARED SETTINGS - ALL targets, ALL configurations =====

_: &CommonSettings

    #--- CUSTOM project-related settings

    _COMPANY_IDENTIFIER: *CompanyIdentifier
    _PROJECT_TITLE: *ProjectTitle

    #--- PROJECT-related settings

    DEVELOPMENT_TEAM: UJA88X59XP # 'Maxim Khatskevich'

    #--- OTHER settings

    SWIFT_VERSION: '3.0'
    SDKROOT: iphoneos
    TARGETED_DEVICE_FAMILY: '1,2'
    VERSIONING_SYSTEM: apple-generic

# /CommonSettings

#=== SHARED SETTINGS - framework target ONLY, ALL configurations =====

_: &FwkCommonSettings

    #--- PROJECT-related settings

    PRODUCT_NAME: $(_PROJECT_TITLE)
    PRODUCT_BUNDLE_IDENTIFIER:  $(_COMPANY_IDENTIFIER).$(PRODUCT_NAME)
    INFOPLIST_FILE: Info/$(PRODUCT_NAME).plist

    #--- OTHER settings

    DEFINES_MODULE: 'YES'
    SKIP_INSTALL: 'YES'

    # DYLIB_COMPATIBILITY_VERSION: '1'
    # DYLIB_CURRENT_VERSION: '6'
    # DYLIB_INSTALL_NAME_BASE: '@rpath'

# /FwkCommonSettings

#=== SHARED SETTINGS - framework unit tests target ONLY, ALL configurations =====

_: &TstFwkCommonSettings

    #--- PROJECT-related settings

    PRODUCT_NAME: $(_PROJECT_TITLE)Tst
    PRODUCT_BUNDLE_IDENTIFIER: $(_COMPANY_IDENTIFIER).$(PRODUCT_NAME)
    INFOPLIST_FILE: Info/$(PRODUCT_NAME).plist

# /TstFwkCommonSettings

#=== SPEC ================

configurations:

    Debug:

        type: debug

        profiles:
        - general:debug
        - ios:debug

        overrides:
            *CommonSettings

    #---
    
    Release:

        type: release

        profiles:
        - general:release
        - ios:release

        overrides:
            *CommonSettings

# /configurations

#===

targets:

    Fwk:

        sources: Src

        type: ':framework'

        profiles:
        - platform:ios
        - framework

        configurations:

            Debug:
                <<: *FwkCommonSettings
                SWIFT_OPTIMIZATION_LEVEL: '-Onone'

            Release:
                *FwkCommonSettings

        # /configurations

        references:
        - sdkroot:Foundation.framework
        - sdkroot:UIKit.framework

    # /Fwk

    #---

    Tst:

        references:
        - Fwk
        
        sources: Tst

        type: ':bundle.unit-test'
        
        profiles:
        - platform:ios
        - bundle.unit-test
        
        configurations:

            Debug:
                <<: *TstFwkCommonSettings
                SWIFT_OPTIMIZATION_LEVEL: '-Onone'

            Release:
                *TstFwkCommonSettings
        
        # /configurations

        references:
        - sdkroot:Foundation.framework
        - sdkroot:UIKit.framework

    # /Tst

# /targets

#===

variants:

    $base:
        abstract: YES

    #---

    Main:
        #

# /variants
