---
version: 1.2.0 # Struct spec version https://github.com/lyptt/struct/wiki/Specfile-format:-v1.2.0

#=== SHARED SETTINGS

# http://stackoverflow.com/a/2063741

_: &CommonSettings
    SWIFT_VERSION: '3.0'

_: &AppCommonSettings
    PRODUCT_NAME: '$(TARGET_NAME)'

#=== SPEC

configurations:

    Debug:

        type: debug

        profiles:
        - general:debug
        - ios:debug

        overrides:
            *CommonSettings
            # GCC_SYMBOLS_PRIVATE_EXTERN: 'NO'
            # SDKROOT: iphoneos
            # TARGETED_DEVICE_FAMILY: '1,2'
            # VERSIONING_SYSTEM: apple-generic

    #---
    
    Release:

        type: release

        profiles:
        - general:release
        - ios:release

        overrides:
            *CommonSettings
            # SDKROOT: iphoneos
            # TARGETED_DEVICE_FAMILY: '1,2'
            # VERSIONING_SYSTEM: apple-generic

# /configurations

#===

targets:

    MKHRequirement:

        sources: Src

        type: ':framework'

        profiles:
        - platform:ios
        - framework

        configurations:

            Debug:
                *AppCommonSettings
                # PRODUCT_NAME: '$(TARGET_NAME)'
                # SWIFT_VERSION: '3.0'
                # CLANG_ENABLE_MODULES: 'YES'
                # CODE_SIGN_IDENTITY[sdk=iphoneos*]: iPhone Developer
                # CURRENT_PROJECT_VERSION: '6'
                # DEBUG_INFORMATION_FORMAT: dwarf
                # DEFINES_MODULE: 'YES'
                # DEVELOPMENT_TEAM: UJA88X59XP
                # DYLIB_COMPATIBILITY_VERSION: '1'
                # DYLIB_CURRENT_VERSION: '6'
                # DYLIB_INSTALL_NAME_BASE: '@rpath'
                # ENABLE_STRICT_OBJC_MSGSEND: 'YES'
                # GCC_NO_COMMON_BLOCKS: 'YES'
                # INFOPLIST_FILE: Info/MKHRequirement.plist
                # INSTALL_PATH: '$(LOCAL_LIBRARY_DIR)/Frameworks'
                # MTL_ENABLE_DEBUG_INFO: 'YES'
                # PRODUCT_BUNDLE_IDENTIFIER: khatskevich.maxim.MKHRequirement
                # SKIP_INSTALL: 'YES'
                # SWIFT_OPTIMIZATION_LEVEL: '-Onone'
                # TARGETED_DEVICE_FAMILY: '1,2'
                # VERSIONING_SYSTEM: apple-generic
                # VERSION_INFO_PREFIX: ''

            Release:
                *AppCommonSettings
                # PRODUCT_NAME: '$(TARGET_NAME)'
                # SWIFT_VERSION: '3.0'
                # CLANG_ENABLE_MODULES: 'YES'
                # CODE_SIGN_IDENTITY[sdk=iphoneos*]: iPhone Developer
                # CURRENT_PROJECT_VERSION: '6'
                # DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
                # DEFINES_MODULE: 'YES'
                # DEVELOPMENT_TEAM: UJA88X59XP
                # DYLIB_COMPATIBILITY_VERSION: '1'
                # DYLIB_CURRENT_VERSION: '6'
                # DYLIB_INSTALL_NAME_BASE: '@rpath'
                # ENABLE_STRICT_OBJC_MSGSEND: 'YES'
                # GCC_NO_COMMON_BLOCKS: 'YES'
                # INFOPLIST_FILE: Info/MKHRequirement.plist
                # INSTALL_PATH: '$(LOCAL_LIBRARY_DIR)/Frameworks'
                # MTL_ENABLE_DEBUG_INFO: 'NO'
                # PRODUCT_BUNDLE_IDENTIFIER: khatskevich.maxim.MKHRequirement
                # SKIP_INSTALL: 'YES'
                # TARGETED_DEVICE_FAMILY: '1,2'
                # VERSIONING_SYSTEM: apple-generic
                # VERSION_INFO_PREFIX: ''

        # /configurations

        references:
        - sdkroot:Foundation.framework
        - sdkroot:UIKit.framework

    # /MKHRequirement

    #---

    MKHRequirementTst:

        sources: Tst

        type: ':bundle.unit-test'
        
        profiles:
        - platform:ios
        - bundle.unit-test
        
        # configurations:

            # Debug:
                # CODE_SIGN_IDENTITY[sdk=iphoneos*]: iPhone Developer
                # DEBUG_INFORMATION_FORMAT: dwarf
                # DEVELOPMENT_TEAM: UJA88X59XP
                # ENABLE_STRICT_OBJC_MSGSEND: 'YES'
                # GCC_NO_COMMON_BLOCKS: 'YES'
                # INFOPLIST_FILE: Info/MKHRequirementTst.plist
                # MTL_ENABLE_DEBUG_INFO: 'YES'
                # PRODUCT_BUNDLE_IDENTIFIER: khatskevich.maxim.MKHRequirementTst
                # SWIFT_OPTIMIZATION_LEVEL: '-Onone'

            # Release:
                # CODE_SIGN_IDENTITY[sdk=iphoneos*]: iPhone Developer
                # DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
                # DEVELOPMENT_TEAM: UJA88X59XP
                # ENABLE_STRICT_OBJC_MSGSEND: 'YES'
                # GCC_NO_COMMON_BLOCKS: 'YES'
                # INFOPLIST_FILE: Info/MKHRequirementTst.plist
                # MTL_ENABLE_DEBUG_INFO: 'NO'
                # PRODUCT_BUNDLE_IDENTIFIER: khatskevich.maxim.MKHRequirementTst
        
        # /configurations

        references:
        - sdkroot:Foundation.framework
        - sdkroot:UIKit.framework

    # /MKHRequirementTst

# /targets

#===

variants:
    
    $base:
        abstract: true

    #---
    
    MKHRequirement:
        # iOSTest:
        #     configuration:
        #         SWIFT_ACTIVE_COMPILATION_CONDITIONS: APP_VARIANT_DEV